language: cpp
dist: xenial
compiler: clang
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq libboost-test-dev
script:
  - cmake -H. -BBuild
  - cmake --build Build
  - cmake --build Build --target test
  - cmake --build Build --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T Build/helloworld-1.0.$TRAVIS_BUILD_NUMBER-Linux.deb -utatyana-otus:$BINTRAY_API_KEY "https://api.bintray.com/content/tatyana-otus/hw_otus/test/$TRAVIS_BUILD_NUMBER/helloworld-1.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
 
  
